context:
  version: "0.3.2"
  python_min: '3.9'

package:
  name: mkdocs-llmstxt
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/m/mkdocs-llmstxt/mkdocs_llmstxt-${{ version }}.tar.gz
    sha256: dd63acb8257fca3244058fd820acd4700c1626dbe48ad3a1a2cc9c599f8e4b7f

build:
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pdm-backend
    - pip
  run:
    - python >=${{ python_min }}
    - beautifulsoup4 >=4.12
    - markdownify >=0.14
    - mdformat >=0.7.21
    - mdformat-tables >=1.0
    - mkdocs >=1.6

tests:
  - python:
      imports:
        - mkdocs_llmstxt
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: MkDocs plugin to generate an /llms.txt file.
  documentation: https://pawamoy.github.io/mkdocs-llmstxt
  license: ISC
  license_file: LICENSE
  homepage: https://pawamoy.github.io/mkdocs-llmstxt/
  repository: https://github.com/pawamoy/mkdocs-llmstxt

extra:
  recipe-maintainers:
    - baszalmstra
